---
title: "Group Project Report Draft"
author: "Connor Harrison, Dong Hoon Lee, Haorui Sun"
date: "April 21, 2019"
output: pdf_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

```{r}
knitr::opts_chunk$set(echo=FALSE)
## Data Wrangling - Won't be included in the knit pdf output.
## filtering by age, selecting variables of interest, creating key indicators

library(haven)
library(tidyverse)

epcg17 <- read_dta("epcg17.dta")

epcg17_new <-  epcg17 %>% 
  filter(., age<36 & bast=="099" & bayr>1975 & ugloanr!="01") %>% 
  # selecting age, race, gender, undergraduate loan amoutn, graduate loan amount, physical disability indicator
  select(age, racethm, ugloanr, gender, grloanr, hcapin,
         #degree information, second to fifth highest degrees, highest degree, most recent degree
         d2dg, d3dg, d4dg, d5dg, dgrdg, mrdg,
         #primary/secondary work activity, public/private status of undergrad institution, year ba received
         actcap:acttch, bapbpr, bayr,
         # reason for changing employer
         chchg:chloc, chot:chsch,
         # visa type for non-US citizen, year highest degree awarded, father and mother's education level
         ctzfor, dgryr, eddad, edmom,
         #region code for employer, detailed employer sector, 
         emrg, emsecdt, facadv:facsoc,
         # hours per week worked, job benefits, job satisfaction, labor force status, looking for work, marital status
         hrswk, jobins:jobproft, jobvac, jobsatis, lfstat, lookwk, marsta,
         # job code for last job, job code for principal job, field of study of BA degree, employer type
         n2ocmlst, n2ocprmg, nbamed, nedtp,
         # reasons for working outside field of highest degree, most important reason for working outside field
         nrchg:nrpay, nrrea,
         # reasons for not working, extent job is related to highest degree, reason worked part-time
         nwfam:nwstu, ocedrlp, pjfam:pjstu,
         # respondent location, salary, satisfaction in prinicipal job for..., spouse working indicator, year principal job started
         resploc, salary, satadv:satsoc, spowk, strtyr,
         # amount still owed from undergrad loan, amount still owed from grad loan, veteran status 
         ugower, grower, vetstat) %>% 
  # creating gender and race indicators
  mutate(., female = ifelse(gender=="F", 1,0)) %>% 
  mutate(., race_white = ifelse(racethm=="5",1,0 )) %>% 
  mutate(., race_black = ifelse(racethm=="3",1,0 )) %>% 
  mutate(., race_hispanic = ifelse(racethm=="4",1,0 )) %>%
  mutate(., race_asian = ifelse(racethm=="1",1,0 )) %>%
  mutate(., race_other = ifelse(racethm=="2" | racethm=="6" | racethm=="7", 1,0)) %>% 
  # replacing 9999998 to NA for salary variable
  mutate(., salary= ifelse(salary==9999998, NA, salary)) %>% 
  # bachelor degree indicator
  mutate(., bachelor_degree= ifelse(mrdg=="1", 1,
                                    ifelse(dgrdg=="1", 1,
                                           ifelse(d2dg=="1", 1,
                                                  ifelse(d3dg=="1", 1,
                                                         ifelse(d4dg=="1",1,
                                                                ifelse(d5dg=="1", 1, 0))))))) %>%
  # master's degree indicator
  mutate(., master_degree= ifelse(mrdg=="2", 1,
                                    ifelse(dgrdg=="2", 1,
                                           ifelse(d2dg=="2", 1,
                                                  ifelse(d3dg=="2", 1,
                                                         ifelse(d4dg=="2",1,
                                                                ifelse(d5dg=="2", 1, 0))))))) %>%
  mutate(., doctorate_degree= ifelse(mrdg=="3", 1,
                                    ifelse(dgrdg=="3", 1,
                                           ifelse(d2dg=="3", 1,
                                                  ifelse(d3dg=="3", 1,
                                                         ifelse(d4dg=="3",1,
                                                                ifelse(d5dg=="3", 1, 0))))))) %>%
  # professional degree
  mutate(., professional_degree= ifelse(mrdg=="4", 1,
                                    ifelse(dgrdg=="4", 1,
                                           ifelse(d2dg=="4", 1,
                                                  ifelse(d3dg=="4", 1,
                                                         ifelse(d4dg=="4",1,
                                                                ifelse(d5dg=="4", 1, 0)))))))
head(epcg17_new)

table(epcg17_new$ugloanr)
```

```{r}
knitr::opts_chunk$set(echo=FALSE)
# Plots

# These are some of the charts I used for data viz class
library(ggplot2)

# visual 1
# Data set for visual 1
dataforplot1 <- epcg17_new %>%
  filter(., jobsatis!="L" & emrg<10) %>% 
  mutate(., racethm_new = ifelse(racethm == 5, "White",
                                 ifelse(racethm == 2 | racethm > 5, "Other",
                                        ifelse(racethm == 1, "Asian",
                                               ifelse(racethm==3, "Black", "Hispanic"))))) %>% 
  mutate(.,emrg_char=ifelse(emrg=="01","New England",
                            ifelse(emrg=="02", "Middle Atlantic",
                                   ifelse(emrg=="03", "East North Central",
                                          ifelse(emrg=="04", "West North Central",
                                                 ifelse(emrg=="05", "South Central",
                                                        ifelse(emrg=="06", "East South Central",
                                                               ifelse(emrg=="07", "West South Central",
                                                                      ifelse(emrg=="08", "Mountain", "Pacific and US Territories"))))))))) %>% 
  mutate(.,emrg_factor=factor(emrg_char, c("New England", "Middle Atlantic", "East North Central", "West North Central",
                                            "South Central", "East South Central", "West South Central",
                                            "Mountain", "Pacific and US Territories")))

# Visual #1
ggplot(data=dataforplot1) +
  geom_density(aes(x=as.numeric(ugloanr), fill=racethm_new), alpha=0.4, position = "stack") +
  facet_wrap(~emrg_factor) +
  scale_x_continuous(name ="Undergraduate Loan Amounts", 
                     breaks = c(2:12),
                     labels = c("$0", "", "", "", "", "$40,001-50,000", "", "", "", "", "More than $90,000" ))+
  labs(title ="Undergraudate Student Loan Borrowing Trend by the Employer Region and the Race of the Respondent",
       caption = "Data: National Survey of College Graduates") +
  theme(axis.title.y = element_blank(),
        panel.background = element_blank(),
        strip.background = element_blank(),
        panel.grid.major.x =element_line(colour = "grey", size = 0.5),
        axis.text.x = element_text(face="bold", 
                                   size=8, angle=25))


## vis 2
# data set for the visual
dataforplot2 <- epcg17_new %>%
  filter(., jobsatis!="L" & emrg<10) %>%
  select(., ugloanr,satsal,emrg) %>% 
  mutate(.,obscount=1) %>%
  mutate(.,ugloanr_group=ifelse(as.numeric(ugloanr)==2, 1,
                                ifelse(as.numeric(ugloanr)>2 & as.numeric(ugloanr)<6,2,
                                       ifelse(as.numeric(ugloanr)>5 & as.numeric(ugloanr)<9, 3,
                                              ifelse(as.numeric(ugloanr)>8 & as.numeric(ugloanr)<12,4,5))))) %>%
  mutate(.,satsal_satisfied = if_else(satsal=="1" | satsal =="2", 1, 0)) %>% 
  group_by(.,ugloanr_group, emrg) %>% 
  summarize(.,mean_satsal_sat=mean(satsal_satisfied),
            obscount=sum(obscount)) %>% 
  mutate(.,emrg_char=ifelse(emrg=="01","New England",
                            ifelse(emrg=="02", "Middle Atlantic",
                                   ifelse(emrg=="03", "East North Central",
                                          ifelse(emrg=="04", "West North Central",
                                                 ifelse(emrg=="05", "South Central",
                                                        ifelse(emrg=="06", "East South Central",
                                                               ifelse(emrg=="07", "West South Central",
                                                                      ifelse(emrg=="08", "Mountain", "Pacific and US Territories"))))))))) %>% 
  filter(., obscount>=50) %>% 
  mutate(.,emrg_factor=factor(emrg_char, c("New England", "Middle Atlantic", "East North Central", "West North Central",
                                            "South Central", "East South Central", "West South Central",
                                            "Mountain", "Pacific and US Territories")))

# Visual 2
ggplot(dataforplot2, aes(x=emrg_factor, y=mean_satsal_sat, color=as.character(ugloanr_group), group=as.character(ugloanr_group))) +
  geom_point() +
  geom_line() +
  scale_color_brewer(name = "Loan Amount",
                     type=qual,
                     palette = "Set1",
                     labels = c("1"="$0", "2"="$1-30,000", "3"="$30,001-60,000", "4"="$60,001-90,000", "5" = "More than $90,000")) +
  labs(title ="Changes in Salary Satisfaction Varies by Undergraduate Loan Amount and Region of Employer",
       caption = "Data: National Survey of College Graduates") +
  theme(axis.title.x = element_blank(),
        axis.title.y = element_blank(),
        panel.background = element_blank(),
        strip.background = element_blank(),
        panel.grid.major.x =element_line(colour = "grey", size = 0.5),
        axis.text.x = element_text(face="bold", 
                                   size=8, angle=20))
```

